In [18]:
import cv2
 
capture = cv2.VideoCapture('test2.mp4')
 
frameNr = 0
n = 1
while (True):
 
    success, frame = capture.read()
 
    if success:
        cv2.imwrite('test2_origin/'+str(n)+'.jpg', frame)
        n += 1
    frame_height = capture.get(cv2.CAP_PROP_FRAME_HEIGHT)
    frame_width = capture.get(cv2.CAP_PROP_FRAME_WIDTH)
    frameNr = frameNr+1
    if not success:
        break
 
print(frameNr)
print(frame_height)
print(frame_width)
capture.release()

632
1080.0
1920.0


In [16]:
import os
image_list = []
# read files
files = os.listdir("test3/")
N = len(files)
files.sort()

print(N)

595


In [39]:
import numpy as np
import cv2 as cv


cap = cv.VideoCapture("/Users/wanyuzhang/Downloads/slow_traffic_small.mp4")

# params for ShiTomasi corner detection
feature_params = dict( maxCorners = 100,
                       qualityLevel = 0.3,
                       minDistance = 7,
                       blockSize = 7 )

# Parameters for lucas kanade optical flow
lk_params = dict( winSize  = (15, 15),
                  maxLevel = 2,
                  criteria = (cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 0.03))

# Create some random colors
color = np.random.randint(0, 255, (100, 3))

# Take first frame and find corners in it
ret, old_frame = cap.read()
old_gray = cv.cvtColor(old_frame, cv.COLOR_BGR2GRAY)
p0 = cv.goodFeaturesToTrack(old_gray, mask = None, **feature_params)

# Create a mask image for drawing purposes
mask = np.zeros_like(old_frame)

while(1):
    ret, frame = cap.read()
    if not ret:
        print('No frames grabbed!')
        break

    frame_gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)

    # calculate optical flow
    p1, st, err = cv.calcOpticalFlowPyrLK(old_gray, frame_gray, p0, None, **lk_params)

    # Select good points
    if p1 is not None:
        good_new = p1[st==1]
        good_old = p0[st==1]

    # draw the tracks
    for i, (new, old) in enumerate(zip(good_new, good_old)):
        a, b = new.ravel()
        c, d = old.ravel()
        mask = cv.line(mask, (int(a), int(b)), (int(c), int(d)), color[i].tolist(), 2)
        frame = cv.circle(frame, (int(a), int(b)), 5, color[i].tolist(), -1)
    img = cv.add(frame, mask)

    cv.imshow('frame', img)
    k = cv.waitKey(30) & 0xff
    if k == 27:
        break

    # Now update the previous frame and previous points
    old_gray = frame_gray.copy()
    p0 = good_new.reshape(-1, 1, 2)

cv.destroyAllWindows()


No frames grabbed!


: 

In [3]:
import cv2
import imutils
if imutils.is_cv4:
    print("yes")

yes


In [4]:
import numpy as np
import cv2 as cv
cap = cv.VideoCapture("/Users/wanyuzhang/Downloads/Video1.mp4")
ret, frame1 = cap.read()
prvs = cv.cvtColor(frame1, cv.COLOR_BGR2GRAY)
hsv = np.zeros_like(frame1)
hsv[..., 1] = 255
while(1):
    ret, frame2 = cap.read()
    if not ret:
        print('No frames grabbed!')
        break
    next = cv.cvtColor(frame2, cv.COLOR_BGR2GRAY)
    flow = cv.calcOpticalFlowFarneback(prvs, next, None, 0.5, 3, 15, 3, 5, 1.2, 0)
    mag, ang = cv.cartToPolar(flow[..., 0], flow[..., 1])
    hsv[..., 0] = ang*180/np.pi/2
    hsv[..., 2] = cv.normalize(mag, None, 0, 255, cv.NORM_MINMAX)
    bgr = cv.cvtColor(hsv, cv.COLOR_HSV2BGR)
    cv.imshow('frame2', bgr)
    k = cv.waitKey(30) & 0xff
    if k == 27:
        break
    elif k == ord('s'):
        cv.imwrite('opticalfb.png', frame2)
        cv.imwrite('opticalhsv.png', bgr)
    prvs = next
cv.destroyAllWindows()


No frames grabbed!


: 

In [38]:
import numpy as np
a  = np.load("/Users/wanyuzhang/Downloads/motion_vectors_stairs/mvs-1.npy")
print(a)
print(len(a))
x = 0
y = 0
for v in a:
    x = max(v[5],x)
    y = max(v[6],y)

print(x)
print(y)

[[-1 16 16 ...  0  0  4]
 [ 1 16 16 ...  0  0  4]
 [-1 16 16 ...  0  0  4]
 ...
 [-1 16  8 ... -1  0  4]
 [ 1 16  8 ... -6  0  4]
 [ 1 16  8 ...  0  0  4]]
14129
1916
1084


In [13]:
import numpy as np 

H = np.array([[ 1.64421178e+00, -4.33825104e-02,  1.59166736e+02],  \
       [ 2.87348665e-01,  1.30082263e+00,  7.95555327e+01], \
       [ 4.20992169e-04,  2.20575083e-05,  8.14858721e-01]])
xh = np.linalg.inv(H)
print(np.dot(xh,np.array([1920,1080,1])))

[1.12076403e+03 5.43929483e+02 6.33446484e-01]
